name: cicd

on:
  - push

jobs:

  Deploy_To_Dev:
      runs-on: ubuntu-latest

      environment: dev            
      steps:
      - name: Checkout Source
        uses: actions/checkout@v2.3.4

      - name: Generate Manifests
        run: |
          .github/workflows/utils/generate-manifests.py
