name: cicd

on:
  - push

jobs:

  Deploy_To_Dev:
      runs-on: ubuntu-latest

    strategy:
      matrix:
        deployment_target:
          - "hello-world-app"

      environment: dev            
      steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Generate Manifests
        run: |
          .github/workflows/utils/generate-manifests.py deploymentTargets/${{ matrix.deployment_target }}
