name: cicd

on:
  - push

jobs:

  Deploy_To_Dev:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        chart_name:
          - "hello-world-app"
      fail-fast: false

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Generate Manifests
        run: |
          .github/workflows/utils/generate-manifests.py \
            ${{ github.workspace }}/deployment/${{ matrix.chart_name }}/deploymentTargets/ \
            ${{ github.workspace }}/charts/${{ matrix.chart_name/ }} \
            ${{ github.workspace }}/generated_manifests